version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HURL_ENV=prod
      - HOST=0.0.0.0
      - PORT=8000
      - HURL_ALLOW_ORIGINS=https://hurl.lol,http://localhost:4000,http://localhost:8000,https://localhost:8000,http://127.0.0.1:4000,http://127.0.0.1:8000
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: hurl-network
